{% set version = "0.7.4" %}
{% set sha256 = "69f209082b495eafac5643ea1d6ab0c6732088b0e5ec43b7963a5fe057aa9da5" %}

package:
  name: chemfiles-python
  version: {{ version }}

source:
  fn: chemfiles.py-{{ version }}.tar.gz
  url: https://github.com/chemfiles/chemfiles.py/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [win and py2k]
  number: 0

requirements:
  build:
    - python
    - cmake
    - setuptools
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib 0.7.*
  run:
    - python
    - enum34  # [py2k]
    - numpy
    - chemfiles-lib 0.7.*

test:
  import:
    - chemfiles

about:
  home: http://chemfiles.org
  license: MPL-v2.0
  license_file: LICENCE.txt
  summary: Python binding to chemfiles, a modern library for chemistry file reading and writing
  doc_url: http://chemfiles.org/chemfiles.py/latest/
  dev_url: https://github.com/chemfiles/chemfiles.py

extra:
  recipe-maintainers:
    - luthaf
